### ISSUE TITLE
SR/PP update checklist 2022-09

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-infrastructure#14]
## Important changes

- osu: Added HD+FL difficulty adjustment mod combination (1032)
- osu: Added TD difficulty adjustment mod (4)
- osu: Added `speed_note_count` difficulty attribute.

## Table setup

- [x] No changes required.
  - Database already contains the new `Speed note count` attribute (`attrib_id = 21`).

## Medal updates

- [x] https://github.com/peppy/osu-web-10/pull/202

## Related PRs

- [x] https://github.com/peppy/osu-web-10/pull/201
- [x] https://github.com/peppy/osu-stable/pull/2412
- [x] https://github.com/ppy/osu-beatmap-difficulty-lookup-cache/pull/11

## Deployment (in order)

Suggested ruleset order:
`taiko -> osu -> mania -> catch`

- [x] `osu-difficulty-calculator` (watch - all rulesets)
- [x] `osu-difficulty-calculator` (reprocess - all rulesets)
- [x] `osu-web-10` (with above PRs)
- [x] `osu-performance` (watch - all rulesets)
- [x] `osu-performance` (reprocess - all rulesets)
- [x] `osu-beatmap-difficulty-lookup-cache` (with above PR)
- [x] `osu-stable` (with above PR)
- [x] `osu-queue-score-statistics` (watch)
- [x] `osu-queue-score-statistics` (`scores all` - all rulesets)

## Wiki

- [x] https://github.com/ppy/osu-wiki/pull/7925
- [x] https://github.com/ppy/osu-wiki/pull/7915
- [x] https://github.com/ppy/osu-wiki/pull/7988

**Comment by Len-Github** [comment]
Any ETA of when this will start going through?

**Comment by peppy** [comment]
No.

**Comment by peppy** [comment]
@smoogipoo I guess for good measure `osu-queue-score-statistics` should be run with `scores all` at some point after the `watch` version is updated, right?

**Comment by peppy** [comment]
In addition, it says "reprocess – all rulesets" but there is no news post for osu!catch, can you clarify on that?

**Comment by smoogipoo** [comment]
> I guess for good measure `osu-queue-score-statistics` should be run with `scores all` at some point

True. Yes, `scores all` should also be run. I'll add that to the description.

> it says "reprocess – all rulesets" but there is no news post for osu!catch

There aren't any catch-specific changes this time around. I mentioned internally that some of the general structural changes may have changed catch values, but looking back on things it doesn't seem like that should be the case. Up to you whether to run it or not. Regardless, it's a very low priority, so I suggest the order of deploy to be:
`taiko -> osu -> mania -> catch`

**Comment by smoogipoo** [comment]
Closing as this has been done.
