### ISSUE TITLE
Redeploy server components with new legacy difficulty attribute storage

### ISSUE THREAD

**Issue by peppy** [ppy/osu-infrastructure#21]
```[tasklist]
### Tasks
- [x] Merge https://github.com/ppy/osu-queue-score-statistics/pull/155
- [x] Merge https://github.com/ppy/osu/pull/24166
- [x] Merge https://github.com/ppy/osu-difficulty-calculator/pull/228
- [x] Merge https://github.com/ppy/osu-queue-score-statistics/pull/179
- [x] Merge https://github.com/ppy/osu-difficulty-calculator/pull/227
- [x] Make osu-web-10 push beatmaps that need processing to a separate redis queue, separate from difficulty processing.
- [x] Deploy `osu-difficulty-calculator`
- [x] Run `osu-difficulty-calculator` in watch mode for the new queue via `dotnet run -- ScoreAttributes {new-queue-name}`
- [x] Run `osu-difficulty-calculator` in once-off mode for the new queue via `dotnet run -- all --processing-mode ScoreAttributes` (or similar)
- [x] Wait for once-off process to complete ^^
- [x] Update `osu-queue-score-statistics` with changes from https://github.com/ppy/osu/pull/25744
- [x] Deploy `osu-queue-score-statistics`
- [x] Run `osu-queue-score-statistics` to import highscores.
```

**Comment by peppy** [comment]
Reassigning this to @smoogipoo. Requirements have likely changed since https://github.com/ppy/osu/pull/24166.

**Comment by smoogipoo** [comment]
I've updated the OP to list the new tasks to be done in order.

**Comment by peppy** [comment]
@smoogipoo do score attribs need to be populated on non-ranked beatmaps? i think we may be able to skip that correct? on rank, it will be processed by the queue.

**Comment by smoogipoo** [comment]
They're not needed for unranked beatmaps as far as I know.

**Comment by peppy** [comment]
@smoogipoo the "deploy `osu-queue-score-statistics` here is unimportant for watch mode correct? It's just listed for the next import step? (I'm currently running these two steps in different locations which is why I ask – if we don't need to deploy to the main queue processor then I probably won't prioritise that part).

**Comment by smoogipoo** [comment]
If I understand correctly, then yes, the deploy I'm referring to is only for the purpose of importing highscores (either the full or the watch mode).

**Comment by peppy** [comment]
Cool. I'm going to close this issue as done, the actual import tasks will be tracked in https://github.com/ppy/osu-infrastructure/issues/23.
